name: Deploy to server via SSH
on:
  push:
    branches:
      - main
jobs:
  deployment:
    name: Deploy to server via SSH
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd open-chats/
            git pull
            pnpm install
            pm2 restart open_chats